name: deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  OWNER: ${{ github.repository_owner }}
  REPO: ${{ github.event.repository.name }}
  BASE_URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true
      - run: hugo --minify --baseURL "${{ env.BASE_URL }}"
      - uses: actions/upload-pages-artifact@v4
        with:
          path: public
      - id: deployment
        uses: actions/deploy-pages@v4
